package com.hyperswitch.common.types;

/**
 * Webhook event types supported by the system
 */
public enum WebhookEventType {
    // Payment events
    PAYMENT_INTENT_SUCCESS,
    PAYMENT_INTENT_FAILURE,
    PAYMENT_INTENT_PROCESSING,
    PAYMENT_INTENT_PARTIALLY_FUNDED,
    PAYMENT_INTENT_CANCELLED,
    PAYMENT_INTENT_CANCEL_FAILURE,
    PAYMENT_INTENT_AUTHORIZATION_SUCCESS,
    PAYMENT_INTENT_AUTHORIZATION_FAILURE,
    PAYMENT_INTENT_EXTEND_AUTHORIZATION_SUCCESS,
    PAYMENT_INTENT_EXTEND_AUTHORIZATION_FAILURE,
    PAYMENT_INTENT_CAPTURE_SUCCESS,
    PAYMENT_INTENT_CAPTURE_FAILURE,
    PAYMENT_INTENT_EXPIRED,
    PAYMENT_ACTION_REQUIRED,
    
    // Refund events
    REFUND_SUCCESS,
    REFUND_FAILURE,
    
    // Dispute events
    DISPUTE_OPENED,
    DISPUTE_EXPIRED,
    DISPUTE_ACCEPTED,
    DISPUTE_CANCELLED,
    DISPUTE_CHALLENGED,
    DISPUTE_WON,
    DISPUTE_LOST,
    
    // Mandate events
    MANDATE_ACTIVE,
    MANDATE_REVOKED,
    
    // Payout events
    PAYOUT_SUCCESS,
    PAYOUT_FAILURE,
    PAYOUT_PROCESSING,
    PAYOUT_CANCELLED,
    PAYOUT_CREATED,
    PAYOUT_EXPIRED,
    PAYOUT_REVERSED,
    
    // Subscription events
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_UPDATED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_ACTIVATED,
    INVOICE_GENERATED,
    
    // Fraud events
    FRM_APPROVED,
    FRM_REJECTED,
    
    // Recovery events
    RECOVERY_PAYMENT_FAILURE,
    
    // Setup/Verification
    SETUP_WEBHOOK,
    ENDPOINT_VERIFICATION,
    EVENT_NOT_SUPPORTED
}

